version: '3'
services:

  syncthing:
    image: linuxserver/syncthing 
    env_file: config/syncthing.env
    environment:
      PUID: ${HOST_USER_ID:?HOST_USER_ID is required}
      PGID: ${HOST_GROUP_ID:?HOST_GROUP_ID is required}
      WATCHTOWER_SCOPE: syncthing-compose
      TZ: ${TZ:-UTC}
    network_mode: host
    volumes:
      - syncthing-config:/config
      - syncthing-data:/data
    labels:
      com.centurylinklabs.watchtower.scope: syncthing-compose
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    env_file: config/watchtower.env
    environment:
      WATCHTOWER_SCOPE: syncthing-compose
      TZ: ${TZ:-UTC}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      com.centurylinklabs.watchtower.scope: syncthing-compose
    restart: unless-stopped

volumes:
  syncthing-config: {}
  syncthing-data: {}
