services:

  syncthing:
    image: syncthing/syncthing${SYNCTHING_VERSION:-latest}
    env_file: config/syncthing.env
    environment:
      PUID: ${HOST_USER_ID:?HOST_USER_ID is required}
      PGID: ${HOST_GROUP_ID:?HOST_GROUP_ID is required}
      WATCHTOWER_SCOPE: ${COMPOSE_PROJECT_NAME}
    network_mode: ${NETWORK_MODE:-host}
    volumes:
      - syncthing-config:/var/syncthing
      - ${SYNCTHING_DATA_DIR:-syncthing-data}:/data
      - /etc/localtime:/etc/localtime:ro
    labels:
      com.centurylinklabs.watchtower.scope: ${COMPOSE_PROJECT_NAME}
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower:${WATCHTOWER_VERSION:-latest}
    env_file: config/watchtower.env
    environment:
      WATCHTOWER_SCOPE: ${COMPOSE_PROJECT_NAME}
      TZ: ${TZ:-UTC}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    labels:
      com.centurylinklabs.watchtower.scope: ${COMPOSE_PROJECT_NAME}
    restart: unless-stopped

volumes:
  syncthing-config: {}
  syncthing-data: {}
