version: '3'
services:

  syncthing:
    image: docker.io/phlak/syncthing
    env_file: config/syncthing.env
    environment:
      TZ: ${TZ:-UTC}
    network_mode: host
    volumes:
      - syncthing-config:/etc/syncthing
      - ${SYNCTHING_DATA_DIR:-syncthing-data}:/vol/storage
    userns_mode: keep-id:uid=1000,gid=1000
    annotations:
      run.oci.keep_original_groups: 1
    restart: unless-stopped

volumes:
  syncthing-config: {}
  syncthing-data: {}
