version: '3'
services:

  syncthing:
    image: linuxserver/syncthing
    env_file: config/syncthing.env
    environment:
      PUID: ${HOST_USER_ID:?HOST_USER_ID is required}
      PGID: ${HOST_GROUP_ID:?HOST_GROUP_ID is required}
      TZ: ${TZ:-UTC}
    network_mode: host
    volumes:
      - syncthing-config:/config
      - ${SYNCTHING_DATA_DIR:-syncthing-data}:/data
    restart: unless-stopped

volumes:
  syncthing-config: {}
  syncthing-data: {}
