services:

  syncthing:
    image: syncthing/syncthing:${SYNCTHING_VERSION:-latest}
    env_file: environment.d/syncthing.env
    environment:
      PUID: ${HOST_USER_ID:?HOST_USER_ID is required}
      PGID: ${HOST_GROUP_ID:?HOST_GROUP_ID is required}
      WATCHTOWER_SCOPE: ${COMPOSE_PROJECT_NAME}
    ports:
      - ${SYNCTHING_WEB_UI_PORT:-8384}:8384
      - ${SYNCTHING_SYNC_PORT:-22000}:22000/tcp
      - ${SYNCTHING_SYNC_PORT:-22000}:22000/udp
      - ${SYNCTHING_DISCOVERY_PORT:-21027}:21027/udp
    volumes:
      - ${SYNCTHING_CONFIG_VOLUME:-syncthing-config}:/var/syncthing
      - ${SYNCTHING_DATA_DIR}:/data
      - /etc/localtime:/etc/localtime:ro
    labels:
      com.centurylinklabs.watchtower.scope: ${COMPOSE_PROJECT_NAME}
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower:${WATCHTOWER_VERSION:-latest}
    env_file: environment.d/watchtower.env
    environment:
      WATCHTOWER_SCOPE: ${COMPOSE_PROJECT_NAME}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    labels:
      com.centurylinklabs.watchtower.scope: ${COMPOSE_PROJECT_NAME}
    restart: unless-stopped

volumes:
  syncthing-config: {}
