services:

  syncthing:
    image: syncthing/syncthing:${SYNCTHING_VERSION:-2}
    env_file: environment.d/syncthing.env
    network_mode: ${NETWORK_MODE:-bridge}
    environment:
      STGUIADDRESS: 127.0.0.1:8384
    ports:
      - ${WEB_PORT:-8384}:8384
      - ${SYNC_PORT:-22000}:22000/tcp
      - ${SYNC_PORT:-22000}:22000/udp
      - ${DISCOVERY_PORT:-21027}:21027/udp
    volumes:
      - ${SYNCTHING_DATA_DIR}:/data
      - ${SYNCTHING_CONFIG_VOLUME:-syncthing-config}:/var/syncthing
      - /etc/localtime:/etc/localtime:ro
    labels:
      com.centurylinklabs.watchtower.scope: ${COMPOSE_PROJECT_NAME}
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower:${WATCHTOWER_VERSION:-latest}
    env_file: environment.d/watchtower.env
    environment:
      WATCHTOWER_SCOPE: ${COMPOSE_PROJECT_NAME}
    volumes:
      - ${DOCKER_SOCKET:-/var/run/docker.sock}:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    labels:
      com.centurylinklabs.watchtower.scope: ${COMPOSE_PROJECT_NAME}
    restart: unless-stopped

volumes:
  syncthing-config: {}
